# Ejercicio 0201

Link: https://drive.google.com/file/d/189zhy8tZcJ6DrTlQsBuB8figmcUhQUwQ/view


## Ejercicios planteados

1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2 matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)
2. Cree una matriz de identidad de dimensión 4.
3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana.
4. Genere una secuencia de números en forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...


In [1]:
%pip install numpy

  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# Definir dos matrices de la misma dimensión
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Sumar las dos matrices
matriz_suma = matriz1 + matriz2

print(matriz_suma)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [4]:
# Crear matriz de identidad de dimensión 4, se asume que es una matriz bidimensional. Por lo que no sería un tensor 4D compuesto de matrices identidad.
identidad = np.eye(4)

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:

# Crear una matriz binaria
binaria = np.array([[0, 1], [1, 0]])

# Convertir a matriz booleana
booleana = binaria.astype(bool)

print(booleana)

[[False  True]
 [ True False]]


In [6]:
# Generar secuencia
secuencia = np.arange(0, 101, 2)

print(secuencia)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
